function i(b){throw b;}var j=void 0,k=!0,m=null,n=!1;function aa(){return function(b){return b}}function ba(b){return function(c){this[b]=c}}function da(b){return function(){return this[b]}}var o,p=this;function ea(b,c){var d=b.split("."),e=p;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&q(c)?e[g]=c:e=e[g]?e[g]:e[g]={}}function fa(){}
function ga(b){var c=typeof b;if("object"==c)if(b){if(b instanceof Array)return"array";if(b instanceof Object)return c;var d=Object.prototype.toString.call(b);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof b.length&&"undefined"!=typeof b.splice&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof b.call&&"undefined"!=typeof b.propertyIsEnumerable&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof b.call)return"object";return c}function q(b){return b!==j}function t(b){return"array"==ga(b)}function v(b){var c=ga(b);return"array"==c||"object"==c&&"number"==typeof b.length}function x(b){return"string"==typeof b}function ha(b){return"number"==typeof b}function y(b){return"function"==ga(b)}function z(b){var c=typeof b;return"object"==c&&b!=m||"function"==c}function A(b){return b[ia]||(b[ia]=++ja)}
var ia="closure_uid_"+Math.floor(2147483648*Math.random()).toString(36),ja=0;function ka(b,c,d){return b.call.apply(b.bind,arguments)}function la(b,c,d){b||i(Error());if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,e);return b.apply(c,d)}}return function(){return b.apply(c,arguments)}}
function B(b,c,d){B=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ka:la;return B.apply(m,arguments)}function ma(b,c){var d=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,d);return b.apply(this,c)}}function D(b,c){function d(){}d.prototype=c.prototype;b.f=c.prototype;b.prototype=new d;b.prototype.constructor=b};function na(){}na.prototype.tb=n;na.prototype.J=function(){this.tb||(this.tb=k,this.t())};na.prototype.t=function(){this.Rb&&oa.apply(m,this.Rb)};function oa(b){for(var c=0,d=arguments.length;c<d;++c){var e=arguments[c];v(e)?oa.apply(m,e):e&&"function"==typeof e.J&&e.J()}};function pa(b){return b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")}var qa=/^[a-zA-Z0-9\-_.!~*'()]*$/;function ra(b){b=""+b;return!qa.test(b)?encodeURIComponent(b):b}function sa(b){if(!ta.test(b))return b;-1!=b.indexOf("&")&&(b=b.replace(ua,"&amp;"));-1!=b.indexOf("<")&&(b=b.replace(va,"&lt;"));-1!=b.indexOf(">")&&(b=b.replace(wa,"&gt;"));-1!=b.indexOf('"')&&(b=b.replace(xa,"&quot;"));return b}var ua=/&/g,va=/</g,wa=/>/g,xa=/\"/g,ta=/[&<>\"]/;
function ya(b){return(""+b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")}var za={};function Aa(b){return za[b]||(za[b]=(""+b).replace(/\-([a-z])/g,function(b,d){return d.toUpperCase()}))};var F=Array.prototype,G=F.indexOf?function(b,c,d){return F.indexOf.call(b,c,d)}:function(b,c,d){d=d==m?0:0>d?Math.max(0,b.length+d):d;if(x(b))return!x(c)||1!=c.length?-1:b.indexOf(c,d);for(;d<b.length;d++)if(d in b&&b[d]===c)return d;return-1},H=F.forEach?function(b,c,d){F.forEach.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=x(b)?b.split(""):b,f=0;f<e;f++)f in g&&c.call(d,g[f],f,b)},Ba=F.filter?function(b,c,d){return F.filter.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=[],f=0,h=x(b)?b.split(""):
b,l=0;l<e;l++)if(l in h){var r=h[l];c.call(d,r,l,b)&&(g[f++]=r)}return g},I=F.map?function(b,c,d){return F.map.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=Array(e),f=x(b)?b.split(""):b,h=0;h<e;h++)h in f&&(g[h]=c.call(d,f[h],h,b));return g};function Ca(b,c,d){var e={};if(b.reduce)return d?b.reduce(B(c,d),e):b.reduce(c,e);var g=e;H(b,function(e,h){g=c.call(d,g,e,h,b)});return g}
var Ha=F.some?function(b,c,d){return F.some.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=x(b)?b.split(""):b,f=0;f<e;f++)if(f in g&&c.call(d,g[f],f,b))return k;return n},Ia=F.every?function(b,c,d){return F.every.call(b,c,d)}:function(b,c,d){for(var e=b.length,g=x(b)?b.split(""):b,f=0;f<e;f++)if(f in g&&!c.call(d,g[f],f,b))return n;return k};function Ja(b,c,d){c=Ka(b,c,d);return 0>c?m:x(b)?b.charAt(c):b[c]}
function Ka(b,c,d){for(var e=b.length,g=x(b)?b.split(""):b,f=0;f<e;f++)if(f in g&&c.call(d,g[f],f,b))return f;return-1}function La(b,c){for(var d=x(b)?b.split(""):b,e=b.length-1;0<=e;e--)if(e in d&&c.call(j,d[e],e,b))return e;return-1}function Ma(b,c){0<=G(b,c)||b.push(c)}function Na(b,c,d){Oa(b,d,0,c)}function Pa(b,c){var d=G(b,c);0<=d&&F.splice.call(b,d,1)}function J(b,c){var d=Ka(b,c,j);return 0<=d?(F.splice.call(b,d,1),k):n}function Qa(b){return F.concat.apply(F,arguments)}
function L(b){if(t(b))return Qa(b);for(var c=[],d=0,e=b.length;d<e;d++)c[d]=b[d];return c}function Ra(b,c){for(var d=1;d<arguments.length;d++){var e=arguments[d],g;if(t(e)||(g=v(e))&&e.hasOwnProperty("callee"))b.push.apply(b,e);else if(g)for(var f=b.length,h=e.length,l=0;l<h;l++)b[f+l]=e[l];else b.push(e)}}function Oa(b,c,d,e){F.splice.apply(b,M(arguments,1))}function M(b,c,d){return 2>=arguments.length?F.slice.call(b,c):F.slice.call(b,c,d)}
function Sa(b,c){for(var d=c||b,e={},g=0,f=0;f<b.length;){var h=b[f++],l=z(h)?"o"+A(h):(typeof h).charAt(0)+h;Object.prototype.hasOwnProperty.call(e,l)||(e[l]=k,d[g++]=h)}d.length=g}function Ta(b,c){if(!v(b)||!v(c)||b.length!=c.length)return n;for(var d=b.length,e=Ua,g=0;g<d;g++)if(!e(b[g],c[g]))return n;return k}function Va(b,c){return b>c?1:b<c?-1:0}function Ua(b,c){return b===c}
function Wa(b){for(var c=[],d=0;d<arguments.length;d++){var e=arguments[d];t(e)?c.push.apply(c,Wa.apply(m,e)):c.push(e)}return c};var Xa,Ya,Za,cb;function db(){return p.navigator?p.navigator.userAgent:m}function eb(){return p.navigator}cb=Za=Ya=Xa=n;var fb;if(fb=db()){var gb=eb();Xa=0==fb.indexOf("Opera");Ya=!Xa&&-1!=fb.indexOf("MSIE");(Za=!Xa&&-1!=fb.indexOf("WebKit"))&&fb.indexOf("Mobile");cb=!Xa&&!Za&&"Gecko"==gb.product}var hb=Xa,N=Ya,ib=cb,O=Za,jb,kb=eb();jb=kb&&kb.platform||"";jb.indexOf("Mac");jb.indexOf("Win");jb.indexOf("Linux");eb()&&(eb().appVersion||"").indexOf("X11");var lb;
a:{var mb="",nb;if(hb&&p.opera)var ob=p.opera.version,mb="function"==typeof ob?ob():ob;else if(ib?nb=/rv\:([^\);]+)(\)|;)/:N?nb=/MSIE\s+([^\);]+)(\)|;)/:O&&(nb=/WebKit\/(\S+)/),nb)var rb=nb.exec(db()),mb=rb?rb[1]:"";if(N){var sb,tb=p.document;sb=tb?tb.documentMode:j;if(sb>parseFloat(mb)){lb=""+sb;break a}}lb=mb}var ub={};
function P(b){var c;if(!(c=ub[b])){c=0;for(var d=pa(""+lb).split("."),e=pa(""+b).split("."),g=Math.max(d.length,e.length),f=0;0==c&&f<g;f++){var h=d[f]||"",l=e[f]||"",r=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var E=r.exec(h)||["","",""],u=s.exec(l)||["","",""];if(0==E[0].length&&0==u[0].length)break;c=((0==E[1].length?0:parseInt(E[1],10))<(0==u[1].length?0:parseInt(u[1],10))?-1:(0==E[1].length?0:parseInt(E[1],10))>(0==u[1].length?0:parseInt(u[1],10))?1:0)||((0==E[2].length)<(0==
u[2].length)?-1:(0==E[2].length)>(0==u[2].length)?1:0)||(E[2]<u[2]?-1:E[2]>u[2]?1:0)}while(0==c)}c=ub[b]=0<=c}return c}var vb={};function wb(b){return vb[b]||(vb[b]=N&&!!document.documentMode&&document.documentMode>=b)};var xb={};!N||wb(9);var yb=!N||wb(9),zb=N&&!P("8");!O||P("528");ib&&P("1.9b")||N&&P("8")||hb&&P("9.5")||O&&P("528");!ib||P("8");function Ab(b,c){this.type=b;this.currentTarget=this.target=c}D(Ab,na);o=Ab.prototype;o.t=function(){delete this.type;delete this.target;delete this.currentTarget};o.Q=n;o.oa=k;o.stopPropagation=function(){this.Q=k};o.preventDefault=function(){this.oa=n};var Bb=N?"focusout":"DOMFocusOut";function Cb(b){Cb[" "](b);return b}Cb[" "]=fa;function Db(b,c){b&&this.M(b,c)}D(Db,Ab);o=Db.prototype;o.target=m;o.relatedTarget=m;o.offsetX=0;o.offsetY=0;o.clientX=0;o.clientY=0;o.screenX=0;o.screenY=0;o.button=0;o.keyCode=0;o.charCode=0;o.ctrlKey=n;o.altKey=n;o.shiftKey=n;o.metaKey=n;o.ba=m;
o.M=function(b,c){var d=this.type=b.type;Ab.call(this,d);this.target=b.target||b.srcElement;this.currentTarget=c;var e=b.relatedTarget;if(e){if(ib){var g;a:{try{Cb(e.nodeName);g=k;break a}catch(f){}g=n}g||(e=m)}}else"mouseover"==d?e=b.fromElement:"mouseout"==d&&(e=b.toElement);this.relatedTarget=e;this.offsetX=O||b.offsetX!==j?b.offsetX:b.layerX;this.offsetY=O||b.offsetY!==j?b.offsetY:b.layerY;this.clientX=b.clientX!==j?b.clientX:b.pageX;this.clientY=b.clientY!==j?b.clientY:b.pageY;this.screenX=b.screenX||
0;this.screenY=b.screenY||0;this.button=b.button;this.keyCode=b.keyCode||0;this.charCode=b.charCode||("keypress"==d?b.keyCode:0);this.ctrlKey=b.ctrlKey;this.altKey=b.altKey;this.shiftKey=b.shiftKey;this.metaKey=b.metaKey;this.state=b.state;this.ba=b;delete this.oa;delete this.Q};o.stopPropagation=function(){Db.f.stopPropagation.call(this);this.ba.stopPropagation?this.ba.stopPropagation():this.ba.cancelBubble=k};
o.preventDefault=function(){Db.f.preventDefault.call(this);var b=this.ba;if(b.preventDefault)b.preventDefault();else if(b.returnValue=n,zb)try{if(b.ctrlKey||112<=b.keyCode&&123>=b.keyCode)b.keyCode=-1}catch(c){}};o.t=function(){Db.f.t.call(this);this.relatedTarget=this.currentTarget=this.target=this.ba=m};function Eb(){}var Fb=0;o=Eb.prototype;o.key=0;o.ja=n;o.qb=n;o.M=function(b,c,d,e,g,f){y(b)?this.yb=k:b&&b.handleEvent&&y(b.handleEvent)?this.yb=n:i(Error("Invalid listener argument"));this.ha=b;this.cb=c;this.src=d;this.type=e;this.capture=!!g;this.fa=f;this.qb=n;this.key=++Fb;this.ja=n};o.handleEvent=function(b){return this.yb?this.ha.call(this.fa||this.src,b):this.ha.handleEvent.call(this.ha,b)};function S(b,c,d){for(var e in b)c.call(d,b[e],e,b)}function Gb(b,c,d){var e={},g;for(g in b)c.call(d,b[g],g,b)&&(e[g]=b[g]);return e}function Hb(b,c){for(var d in b)if(c.call(j,b[d],d,b))return k;return n}function Ib(b){var c=[],d=0,e;for(e in b)c[d++]=b[e];return c}function Jb(b){var c=[],d=0,e;for(e in b)c[d++]=e;return c}function Kb(b,c){var d;(d=c in b)&&delete b[c];return d}function Lb(b,c,d){c in b&&i(Error('The object already contains the key "'+c+'"'));b[c]=d}function Mb(b,c,d){b[c]=d}
function Nb(b){var c={},d;for(d in b)c[d]=b[d];return c}function Ob(b){var c=ga(b);if("object"==c||"array"==c){if(b.I)return b.I();var c="array"==c?[]:{},d;for(d in b)c[d]=Ob(b[d]);return c}return b}var Pb="constructor,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,toLocaleString,toString,valueOf".split(",");function Qb(b,c){for(var d,e,g=1;g<arguments.length;g++){e=arguments[g];for(d in e)b[d]=e[d];for(var f=0;f<Pb.length;f++)d=Pb[f],Object.prototype.hasOwnProperty.call(e,d)&&(b[d]=e[d])}};var Rb={},T={},U={},Sb={};
function Tb(b,c,d,e,g){if(c){if(t(c)){for(var f=0;f<c.length;f++)Tb(b,c[f],d,e,g);return m}var e=!!e,h=T;c in h||(h[c]={d:0,w:0});h=h[c];e in h||(h[e]={d:0,w:0},h.d++);var h=h[e],l=A(b),r;h.w++;if(h[l]){r=h[l];for(f=0;f<r.length;f++)if(h=r[f],h.ha==d&&h.fa==g){if(h.ja)break;return r[f].key}}else r=h[l]=[],h.d++;f=Ub();f.src=b;h=new Eb;h.M(d,f,b,c,e,g);d=h.key;f.key=d;r.push(h);Rb[d]=h;U[l]||(U[l]=[]);U[l].push(h);b.addEventListener?(b==p||!b.sb)&&b.addEventListener(c,f,e):b.attachEvent(c in Sb?Sb[c]:
Sb[c]="on"+c,f);return d}i(Error("Invalid event type"))}function Ub(){var b=Vb,c=yb?function(d){return b.call(c.src,c.key,d)}:function(d){d=b.call(c.src,c.key,d);if(!d)return d};return c}function Wb(b,c,d,e,g){if(t(c))for(var f=0;f<c.length;f++)Wb(b,c[f],d,e,g);else if(e=!!e,b=Xb(b,c,e))for(f=0;f<b.length;f++)if(b[f].ha==d&&b[f].capture==e&&b[f].fa==g){Yb(b[f].key);break}}
function Yb(b){if(!Rb[b])return n;var c=Rb[b];if(c.ja)return n;var d=c.src,e=c.type,g=c.cb,f=c.capture;d.removeEventListener?(d==p||!d.sb)&&d.removeEventListener(e,g,f):d.detachEvent&&d.detachEvent(e in Sb?Sb[e]:Sb[e]="on"+e,g);d=A(d);g=T[e][f][d];if(U[d]){var h=U[d];Pa(h,c);0==h.length&&delete U[d]}c.ja=k;g.Bb=k;Zb(e,f,d,g);delete Rb[b];return k}
function Zb(b,c,d,e){if(!e.za&&e.Bb){for(var g=0,f=0;g<e.length;g++)e[g].ja?e[g].cb.src=m:(g!=f&&(e[f]=e[g]),f++);e.length=f;e.Bb=n;0==f&&(delete T[b][c][d],T[b][c].d--,0==T[b][c].d&&(delete T[b][c],T[b].d--),0==T[b].d&&delete T[b])}}function $b(b){var c,d=0,e=c==m;c=!!c;if(b==m)S(U,function(b){for(var g=b.length-1;0<=g;g--){var f=b[g];if(e||c==f.capture)Yb(f.key),d++}});else if(b=A(b),U[b])for(var b=U[b],g=b.length-1;0<=g;g--){var f=b[g];if(e||c==f.capture)Yb(f.key),d++}}
function Xb(b,c,d){var e=T;return c in e&&(e=e[c],d in e&&(e=e[d],b=A(b),e[b]))?e[b]:m}function ac(b,c,d,e,g){var f=1,c=A(c);if(b[c]){b.w--;b=b[c];b.za?b.za++:b.za=1;try{for(var h=b.length,l=0;l<h;l++){var r=b[l];r&&!r.ja&&(f&=bc(r,g)!==n)}}finally{b.za--,Zb(d,e,c,b)}}return Boolean(f)}function bc(b,c){var d=b.handleEvent(c);b.qb&&Yb(b.key);return d}
function Vb(b,c){if(!Rb[b])return k;var d=Rb[b],e=d.type,g=T;if(!(e in g))return k;var g=g[e],f,h;if(!yb){var l;if(!(l=c))a:{l=["window","event"];for(var r=p;f=l.shift();)if(r[f]!=m)r=r[f];else{l=m;break a}l=r}f=l;l=k in g;r=n in g;if(l){if(0>f.keyCode||f.returnValue!=j)return k;a:{var s=n;if(0==f.keyCode)try{f.keyCode=-1;break a}catch(E){s=k}if(s||f.returnValue==j)f.returnValue=k}}s=new Db;s.M(f,this);f=k;try{if(l){for(var u=[],W=s.currentTarget;W;W=W.parentNode)u.push(W);h=g[k];h.w=h.d;for(var K=
u.length-1;!s.Q&&0<=K&&h.w;K--)s.currentTarget=u[K],f&=ac(h,u[K],e,k,s);if(r){h=g[n];h.w=h.d;for(K=0;!s.Q&&K<u.length&&h.w;K++)s.currentTarget=u[K],f&=ac(h,u[K],e,n,s)}}else f=bc(d,s)}finally{u&&(u.length=0),s.J()}return f}e=new Db(c,this);try{f=bc(d,e)}finally{e.J()}return f};function ec(){}D(ec,na);o=ec.prototype;o.sb=k;o.Ca=m;o.hb=ba("Ca");o.addEventListener=function(b,c,d,e){Tb(this,b,c,d,e)};o.removeEventListener=function(b,c,d,e){Wb(this,b,c,d,e)};
o.dispatchEvent=function(b){var c=b.type||b,d=T;if(c in d){if(x(b))b=new Ab(b,this);else if(b instanceof Ab)b.target=b.target||this;else{var e=b,b=new Ab(c,this);Qb(b,e)}var e=1,g,d=d[c],c=k in d,f;if(c){g=[];for(f=this;f;f=f.Ca)g.push(f);f=d[k];f.w=f.d;for(var h=g.length-1;!b.Q&&0<=h&&f.w;h--)b.currentTarget=g[h],e&=ac(f,g[h],b.type,k,b)&&b.oa!=n}if(n in d)if(f=d[n],f.w=f.d,c)for(h=0;!b.Q&&h<g.length&&f.w;h++)b.currentTarget=g[h],e&=ac(f,g[h],b.type,n,b)&&b.oa!=n;else for(g=this;!b.Q&&g&&f.w;g=g.Ca)b.currentTarget=
g,e&=ac(f,g,b.type,n,b)&&b.oa!=n;b=Boolean(e)}else b=k;return b};o.t=function(){ec.f.t.call(this);$b(this);this.Ca=m};var fc=p.window;var gc,hc=!N||wb(9),ic=!ib&&!N||N&&wb(9)||ib&&P("1.9.1");N&&P("9");function jc(b){return(b=b.className)&&"function"==typeof b.split?b.split(/\s+/):[]}function kc(b,c){var d=jc(b),e=M(arguments,1),g;g=d;for(var f=0,h=0;h<e.length;h++)0<=G(g,e[h])||(g.push(e[h]),f++);g=f==e.length;b.className=d.join(" ");return g}function lc(b,c){for(var d=jc(b),e=M(arguments,1),g=d,f=0,h=0;h<g.length;h++)0<=G(e,g[h])&&(Oa(g,h--,1),f++);b.className=d.join(" ")};function mc(b,c){this.x=q(b)?b:0;this.y=q(c)?c:0}mc.prototype.I=function(){return new mc(this.x,this.y)};mc.prototype.toString=function(){return"("+this.x+", "+this.y+")"};function nc(b,c){this.width=b;this.height=c}nc.prototype.I=function(){return new nc(this.width,this.height)};nc.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};nc.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};function oc(b){return b?new pc(qc(b)):gc||(gc=new pc)}function rc(b,c,d){return sc(b,c,d)}function tc(b,c){var d=c||document;return uc(d)?d.querySelectorAll("."+b):d.getElementsByClassName?d.getElementsByClassName(b):sc("*",b,c)}function uc(b){return b.querySelectorAll&&b.querySelector&&(!O||"CSS1Compat"==document.compatMode||P("528"))}
function sc(b,c,d){d=d||document;b=b&&"*"!=b?b.toUpperCase():"";if(uc(d)&&(b||c))return d.querySelectorAll(b+(c?"."+c:""));if(c&&d.getElementsByClassName){d=d.getElementsByClassName(c);if(b){for(var e={},g=0,f=0,h;h=d[f];f++)b==h.nodeName&&(e[g++]=h);e.length=g;return e}return d}d=d.getElementsByTagName(b||"*");if(c){e={};for(f=g=0;h=d[f];f++)b=h.className,"function"==typeof b.split&&0<=G(b.split(/\s+/),c)&&(e[g++]=h);e.length=g;return e}return d}
function vc(b,c){S(c,function(c,e){"style"==e?b.style.cssText=c:"class"==e?b.className=c:"for"==e?b.htmlFor=c:e in wc?b.setAttribute(wc[e],c):0==e.lastIndexOf("aria-",0)?b.setAttribute(e,c):b[e]=c})}var wc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder",maxlength:"maxLength",type:"type"};
function xc(b,c,d,e){function g(d){d&&c.appendChild(x(d)?b.createTextNode(d):d)}for(;e<d.length;e++){var f=d[e];v(f)&&!(z(f)&&0<f.nodeType)?H(yc(f)?L(f):f,g):g(f)}}function zc(b){var c=document,d=c.createElement("div");N?(d.innerHTML="<br>"+b,d.removeChild(d.firstChild)):d.innerHTML=b;if(1==d.childNodes.length)return d.removeChild(d.firstChild);for(b=c.createDocumentFragment();d.firstChild;)b.appendChild(d.firstChild);return b}function Ac(b,c){xc(qc(b),b,arguments,1)}
function Bc(b){for(var c;c=b.firstChild;)b.removeChild(c)}function Cc(b,c){c.parentNode&&c.parentNode.insertBefore(b,c)}function Dc(b){b&&b.parentNode&&b.parentNode.removeChild(b)}function Ec(b){return ic&&b.children!=j?b.children:Ba(b.childNodes,function(b){return 1==b.nodeType})}function Fc(b,c){if(b.contains&&1==c.nodeType)return b==c||b.contains(c);if("undefined"!=typeof b.compareDocumentPosition)return b==c||Boolean(b.compareDocumentPosition(c)&16);for(;c&&b!=c;)c=c.parentNode;return c==b}
function qc(b){return 9==b.nodeType?b:b.ownerDocument||b.document}function yc(b){if(b&&"number"==typeof b.length){if(z(b))return"function"==typeof b.item||"string"==typeof b.item;if(y(b))return"function"==typeof b.item}return n}function pc(b){this.K=b||p.document||document}o=pc.prototype;o.B=function(b){return x(b)?this.K.getElementById(b):b};
o.T=function(b,c,d){var e=this.K,g=arguments,f=g[0],h=g[1];if(!hc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',sa(h.name),'"');if(h.type){f.push(' type="',sa(h.type),'"');var l={};Qb(l,h);h=l;delete h.type}f.push(">");f=f.join("")}f=e.createElement(f);h&&(x(h)?f.className=h:t(h)?kc.apply(m,[f].concat(h)):vc(f,h));2<g.length&&xc(e,f,g,2);return f};o.createElement=function(b){return this.K.createElement(b)};o.createTextNode=function(b){return this.K.createTextNode(b)};
o.appendChild=function(b,c){b.appendChild(c)};o.contains=Fc;function Gc(b,c,d,e){this.left=b;this.top=c;this.width=d;this.height=e}Gc.prototype.I=function(){return new Gc(this.left,this.top,this.width,this.height)};Gc.prototype.toString=function(){return"("+this.left+", "+this.top+" - "+this.width+"w x "+this.height+"h)"};
Gc.prototype.contains=function(b){return b instanceof Gc?this.left<=b.left&&this.left+this.width>=b.left+b.width&&this.top<=b.top&&this.top+this.height>=b.top+b.height:b.x>=this.left&&b.x<=this.left+this.width&&b.y>=this.top&&b.y<=this.top+this.height};function Hc(b,c,d){b.style[Aa(d)]=c}function Ic(b,c){var d=qc(b);return d.defaultView&&d.defaultView.getComputedStyle&&(d=d.defaultView.getComputedStyle(b,m))?d[c]||d.getPropertyValue(c):""}function Jc(b,c){return Ic(b,c)||(b.currentStyle?b.currentStyle[c]:m)||b.style&&b.style[c]}function Kc(b){var c=b.getBoundingClientRect();N&&(b=b.ownerDocument,c.left-=b.documentElement.clientLeft+b.body.clientLeft,c.top-=b.documentElement.clientTop+b.body.clientTop);return c}
function Lc(b){if(N&&!wb(8))return b.offsetParent;for(var c=qc(b),d=Jc(b,"position"),e="fixed"==d||"absolute"==d,b=b.parentNode;b&&b!=c;b=b.parentNode)if(d=Jc(b,"position"),e=e&&"static"==d&&b!=c.documentElement&&b!=c.body,!e&&(b.scrollWidth>b.clientWidth||b.scrollHeight>b.clientHeight||"fixed"==d||"absolute"==d||"relative"==d))return b;return m}
function Mc(b){var c=b.offsetWidth,d=b.offsetHeight,e=O&&!c&&!d;return(!q(c)||e)&&b.getBoundingClientRect?(b=Kc(b),new nc(b.right-b.left,b.bottom-b.top)):new nc(c,d)}
function Nc(b){var c,d=qc(b),e=Jc(b,"position"),g=ib&&d.getBoxObjectFor&&!b.getBoundingClientRect&&"absolute"==e&&(c=d.getBoxObjectFor(b))&&(0>c.screenX||0>c.screenY),f=new mc(0,0),h;c=d?9==d.nodeType?d:qc(d):document;if(h=N)if(h=!wb(9))h="CSS1Compat"!=oc(c).K.compatMode;h=h?c.body:c.documentElement;if(b!=h)if(b.getBoundingClientRect)c=Kc(b),e=oc(d).K,d=!O&&"CSS1Compat"==e.compatMode?e.documentElement:e.body,e=e.parentWindow||e.defaultView,d=new mc(e.pageXOffset||d.scrollLeft,e.pageYOffset||d.scrollTop),
f.x=c.left+d.x,f.y=c.top+d.y;else if(d.getBoxObjectFor&&!g)c=d.getBoxObjectFor(b),d=d.getBoxObjectFor(h),f.x=c.screenX-d.screenX,f.y=c.screenY-d.screenY;else{c=b;do{f.x+=c.offsetLeft;f.y+=c.offsetTop;c!=b&&(f.x+=c.clientLeft||0,f.y+=c.clientTop||0);if(O&&"fixed"==Jc(c,"position")){f.x+=d.body.scrollLeft;f.y+=d.body.scrollTop;break}c=c.offsetParent}while(c&&c!=b);if(hb||O&&"absolute"==e)f.y-=d.body.offsetTop;for(c=b;(c=Lc(c))&&c!=d.body&&c!=h;)if(f.x-=c.scrollLeft,!hb||"TR"!=c.tagName)f.y-=c.scrollTop}"none"!=
Jc(b,"display")?b=Mc(b):(c=b.style,d=c.display,e=c.visibility,g=c.position,c.visibility="hidden",c.position="absolute",c.display="inline",b=Mc(b),c.display=d,c.position=g,c.visibility=e);return new Gc(f.x,f.y,b.width,b.height)};function Oc(b){if("function"==typeof b.U)return b.U();if(x(b))return b.split("");if(v(b)){for(var c=[],d=b.length,e=0;e<d;e++)c.push(b[e]);return c}return Ib(b)}function Pc(b){if("function"==typeof b.da)return b.da();if("function"!=typeof b.U){if(v(b)||x(b)){for(var c=[],b=b.length,d=0;d<b;d++)c.push(d);return c}return Jb(b)}}function Qc(b,c,d){if("function"==typeof b.forEach)b.forEach(c,d);else if(v(b)||x(b))H(b,c,d);else for(var e=Pc(b),g=Oc(b),f=g.length,h=0;h<f;h++)c.call(d,g[h],e&&e[h],b)};function Rc(b,c){this.H={};this.j=[];var d=arguments.length;if(1<d){d%2&&i(Error("Uneven number of arguments"));for(var e=0;e<d;e+=2)this.set(arguments[e],arguments[e+1])}else if(b){b instanceof Rc?(d=b.da(),e=b.U()):(d=Jb(b),e=Ib(b));for(var g=0;g<d.length;g++)this.set(d[g],e[g])}}o=Rc.prototype;o.d=0;o.U=function(){Sc(this);for(var b=[],c=0;c<this.j.length;c++)b.push(this.H[this.j[c]]);return b};o.da=function(){Sc(this);return this.j.concat()};o.S=function(b){return Tc(this.H,b)};
o.remove=function(b){return Tc(this.H,b)?(delete this.H[b],this.d--,this.j.length>2*this.d&&Sc(this),k):n};function Sc(b){if(b.d!=b.j.length){for(var c=0,d=0;c<b.j.length;){var e=b.j[c];Tc(b.H,e)&&(b.j[d++]=e);c++}b.j.length=d}if(b.d!=b.j.length){for(var g={},d=c=0;c<b.j.length;)e=b.j[c],Tc(g,e)||(b.j[d++]=e,g[e]=1),c++;b.j.length=d}}o.get=function(b,c){return Tc(this.H,b)?this.H[b]:c};o.set=function(b,c){Tc(this.H,b)||(this.d++,this.j.push(b));this.H[b]=c};o.I=function(){return new Rc(this)};
function Tc(b,c){return Object.prototype.hasOwnProperty.call(b,c)};function Uc(b,c,d){this.G=b||m;this.Eb=c||m;this.Xb=!!d}function Vc(b){if(!b.g&&(b.g=new Rc,b.d=0,b.G))for(var c=b.G.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),g=m,f=m;0<=e?(g=c[d].substring(0,e),f=c[d].substring(e+1)):g=c[d];g=decodeURIComponent(g.replace(/\+/g," "));g=Wc(b,g);b.add(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}
function Xc(b){var c=Pc(b);"undefined"==typeof c&&i(Error("Keys are undefined"));b=Oc(b);c.length!=b.length&&i(Error("Mismatched lengths for keys/values"));for(var d=new Uc(m,j,j),e=0;e<c.length;e++)d.add(c[e],b[e]);return d}o=Uc.prototype;o.g=m;o.d=m;o.add=function(b,c){Vc(this);Yc(this);b=Wc(this,b);if(this.S(b)){var d=this.g.get(b);t(d)?d.push(c):this.g.set(b,[d,c])}else this.g.set(b,c);this.d++;return this};
o.remove=function(b){Vc(this);b=Wc(this,b);if(this.g.S(b)){Yc(this);var c=this.g.get(b);t(c)?this.d-=c.length:this.d--;return this.g.remove(b)}return n};o.S=function(b){Vc(this);b=Wc(this,b);return this.g.S(b)};o.da=function(){Vc(this);for(var b=this.g.U(),c=this.g.da(),d=[],e=0;e<c.length;e++){var g=b[e];if(t(g))for(var f=0;f<g.length;f++)d.push(c[e]);else d.push(c[e])}return d};
o.U=function(b){Vc(this);if(b)if(b=Wc(this,b),this.S(b)){var c=this.g.get(b);if(t(c))return c;b=[];b.push(c)}else b=[];else for(var c=this.g.U(),b=[],d=0;d<c.length;d++){var e=c[d];t(e)?Ra(b,e):b.push(e)}return b};o.set=function(b,c){Vc(this);Yc(this);b=Wc(this,b);if(this.S(b)){var d=this.g.get(b);t(d)?this.d-=d.length:this.d--}this.g.set(b,c);this.d++;return this};o.get=function(b,c){Vc(this);b=Wc(this,b);if(this.S(b)){var d=this.g.get(b);return t(d)?d[0]:d}return c};
o.toString=function(){if(this.G)return this.G;if(!this.g)return"";for(var b=[],c=0,d=this.g.da(),e=0;e<d.length;e++){var g=d[e],f=ra(g),g=this.g.get(g);if(t(g))for(var h=0;h<g.length;h++)0<c&&b.push("&"),b.push(f),""!==g[h]&&b.push("=",ra(g[h])),c++;else 0<c&&b.push("&"),b.push(f),""!==g&&b.push("=",ra(g)),c++}return this.G=b.join("")};function Yc(b){delete b.Sa;delete b.G;b.Eb&&delete b.Eb.lc}o.I=function(){var b=new Uc;this.Sa&&(b.Sa=this.Sa);this.G&&(b.G=this.G);this.g&&(b.g=this.g.I());return b};
function Wc(b,c){var d=""+c;b.Xb&&(d=d.toLowerCase());return d}o.extend=function(b){for(var c=0;c<arguments.length;c++)Qc(arguments[c],function(b,c){this.add(c,b)},this)};function V(b,c){b!=m||(b=[]);if(b.constructor==V)return new Zc(id(b));x(c)&&(c=X.Ua(c)[0]);b.constructor==document.createDocumentFragment().constructor&&b.childNodes.length&&(b=L(b.childNodes));b.nodeType?b=[b]:(x(b)&&("<"==b.replace(/^[\s\xa0]+/,"").charAt(0)?(b=zc(b),b=b.constructor==document.createDocumentFragment().constructor&&b.childNodes.length?L(b.childNodes):[b]):b=X.Ua(b,c)),b||(b=[]));"object"===typeof b&&"setInterval"in b?b=[b]:v(b)||(b=[b]);return new Zc(b)}var Y=V,X={},jd=X;
V.prototype.length=0;function Zc(b){for(var c=0;c<b.length;c++)this[c]=b[c];this.length=b.length;return this}X.p=Zc.prototype=V.prototype;V.prototype.constructor=V;X.Ea=m;X.Ab=m;X.gc=function(){X.Ea=kd};X.yc=function(b){X.Ea=b};
X.Pb={visible:function(b){return V(b).ib()},hidden:function(b){return!V(b).ib()},selected:function(b){return b.selected},checked:function(b){return b.checked},first:function(b){return b==b.parentNode.firstChild},last:function(b){return b==b.parentNode.lastChild},even:function(b){return 0===V(b.parentNode).children().index(b)%2},odd:function(b){return 1===V(b.parentNode).children().index(b)%2}};
X.Ua=function(b,c){"-"==b.charAt(0)&&(b="."+b.substring(1));if(X.Ea)return X.Ea(b,c);var d,c=c||document;d=c.querySelectorAll?c.querySelectorAll(0<=b.indexOf(":")?b.replace(/\:.*/,""):b):"."==b.charAt(0)?tc(b.substring(1).replace(/[\:\s].*/,""),c)||[]:"#"==b.charAt(0)?[x(b)?document.getElementById(b):b]:rc(b.replace(/\s.*/,""),b.replace(/.*\./,"").replace(/[\:\s].*/,"")||m,c);return 0<=b.indexOf(":")?X.Sb(d,X.Pb[b.substring(b.indexOf(":")+1)]):d};
X.Ya=function(b,c){c&&"-"==c.charAt(0)&&(c="."+c.substring(1));if(X.Ab)return X.Ab(b,c);if(!q(c))return k;if(y(c))return c(b);var d=b.webkitMatchesSelector||b.mozMatchesSelector||b.oMatchesSelector||b.matchesSelector;if(d)return d.call(b,c);d=X.Ua(c,b.parentNode);return 0<=G(d,b)};X.extend=function(b,c){Qb(b,c);return b};X.contains=Fc;X.data=function(b,c,d){return V(b).data(c,d)};X.i=function(b,c){return V(b).i(c)};X.Sb=function(b,c){return Ba(b,c)};
X.Ac=function(b,c,d){y(b)?d&&(b=B(b,d)):b&&"function"==typeof b.handleEvent?b=B(b.handleEvent,b):i(Error("Invalid listener argument"));return 2147483647<c?-1:fc.setTimeout(b,c||0)};X.mc=function(b){fc.clearTimeout(b)};X.pc=function(b,c,d){return G(c,b,d)};X.ub=function(b){for(var c=[],d=0;d<arguments.length;d++){var e=arguments[d];v(e)?c.push.apply(c,X.ub.apply(m,e)):c.push(e)}return c};X.map=function(b,c){var d;if(v(b))d=I(b,c);else{d={};for(var e in b)d[e]=c.call(j,b[e],e,b)}return d};
X.wc=function(b){function c(b,c){return!t(b)&&z(b)?(S(b,function(b,e){d[c+"["+e+"]"]=b}),delete d[c],k):n}for(var d=Nb(b),b=n;b;)b=Hb(d,c);return Xc(d).toString()};X.qc=Qa;
X.xc=function(b){b=""+b;if(/^\s*$/.test(b)?0:/^[\],:{}\s\u2028\u2029]*$/.test(b.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+b+")")}catch(c){}i(Error("Invalid JSON string: "+b))};X.cb=B;X.trim=pa;X.unique=Sa;X.uc=fa;o=V.prototype;o.i=function(b,c){H(this,function(d,e){b.call(c||d,d,e)});return this};
o.sort=function(b,c){F.sort.call(this,B(b||Va,c||this));return this};o.filter=function(b,c,d){if(x(b)){var e=b;this.size();b={":odd":function(b,c){return 1===c%2},":even":function(b,c){return 0===c%2},":first":function(b,c){return 0===c},":last":function(b,c){return c===this.length-1}}[e];c=this}return V(Ba(this,function(e,f){return Boolean(d)!=Boolean(b.call(c||this,e,f))}))};o.map=function(b,c){return V(I(this,b,c))};o.contains=function(b){return 0<=G(this,b)};
o.get=function(b,c){if(y(b))return Ja(this,b,c);0>b&&(b=this.length+b);return this[b||0]};function id(b){var c=[];b.i(function(b){c.push(b)});return c}o.size=da("length");o.add=function(b){for(var b=V(b),c=b.length,d=this.length,e=0;e<c;e++)this[e+d]=b[e];this.length=c+d;return this};o.remove=function(b){if(v(b))return V(b).i(function(b){this.remove(b)},this);var c=id(this);Pa(c,b);return V(c)};
function ld(b,c,d){x(c)&&!q(d)?N?b[0].currentStyle&&Aa(c):Ic(b[0],c):b.i(function(b){x(c)?Hc(b,d,c):S(c,ma(Hc,b))})}o.top=function(b){return q(b)?(ha(b)&&(b+="px"),this.i(function(c){c.style.top=b}),this):Nc(this.get(0)).top};o.position=function(){return Nc(this[0])};o.left=function(b){return q(b)?(ha(b)&&(b+="px"),this.i(function(c){c.style.left=b}),this):Nc(this.get(0)).left};o.width=function(b){return q(b)?(ha(b)&&(b+="px"),this.i(function(c){c.style.width=b}),this):Nc(this.get(0)).width};
o.index=function(b){return Ka(id(this),function(c){return b.nodeType?c==b:X.Ya(c,b)})};o.height=function(b){return q(b)?(ha(b)&&(b+="px"),this.i(function(c){c.style.height=b}),this):Nc(this.get(0)).height};o.ib=function(b){if(!q(b))return"none"!=this[0].style.display;if("boolean"==typeof b)var c=b,b=function(){return c};var d=b;return this.i(function(b){var c=d(b);b.style.display=c?"":"none"})};o.show=function(){return this.ib(k)};
o.r=function(b,c){if(x(b)&&!q(c))return this[0].getAttribute(b);if(x(b)){var d={};d[b]=c;b=d}z(b)&&this.i(function(c){vc(c,b)});return this};o.data=function(b,c){return this.r("data-"+(b||"id"),c)};o.replace=function(b){v(b)&&(b=b[0]);var c=this[0],d=c.parentNode;d&&d.replaceChild(b,c);return V(b)};function md(b){return q(j)?b.i(function(b){b.value=j}):b[0].value}o.V=function(){return this.map(function(b){return b.previousSibling})};
o.children=function(b){var c=[];this.i(function(b){c=Qa(c,[].slice.call(Ec(b)))});X.unique(c);return q(b)?V(c).filter(function(c){return X.Ya(c,b)}):V(c)};function nd(){var b=Y("<button>Randomize</button>"),c=V(document.body),d=document.createDocumentFragment();b.i(function(b){Ac(d,b)});Ac(c[0],d);return b}function od(b,c){if(b.size()){var c=V(c),d=document.createDocumentFragment();c.i(function(b){Ac(d,b)});1==b.size()?Cc(d,b[0]):b.i(function(b){Cc(d.cloneNode(k),b)})}}
o.insertBefore=function(b){od(V(b),this);return this};o.I=function(b){return this.map(function(c){return c.cloneNode(b)})};o.q=function(b,c,d,e,g,f,h){function l(b){b.data||(b.data=d);(!x(c)||b.target.nodeType&&X.Ya(b.target,c))&&e.call(this,b)}y(c)?(h=g,f=e,g=d,e=c,c=m,d=j):y(d)&&(h=f,g=e,e=d,d=j,z(c)&&(d=c,c=m));l.p=e;return this.map(function(c){return f?(c=pd(f,c,b,l,!!h,g||c),c.j[c.j.length-1]):Tb(c,b,l,!!h,g||c)})};o.bind=V.prototype.q;
o.P=function(b,c,d,e){return!q(b)?(X.P(this),this):this.i(function(g){for(var f=Xb(g,b||"",n)||[],h=0;h<f.length;h++)if(f[h].ha.p==c&&f[h].capture===n&&f[h].fa==(d||g))return(e||xb).zc(f[h].key)})};X.q=Tb;X.P=function(b){var c=n;V(X.ub(b)).i(function(b){c=Yb(b)||c});return c};V.prototype.b=V.prototype.P;V.prototype.click=function(b,c,d){return!b?(qd(this,"click"),this):this.q("click",b,c,d)};V.prototype.la=function(b,c,d){return!b?(qd(this,"change"),this):this.q("change",b,c,d)};
V.prototype.blur=function(b,c,d){return!b?(this[0].blur(),this):N?this.q(Bb,b,c,d):this.q("blur",b,c,d,k)};function qd(b,c){var d;b.i(function(b){d||(d=document.createEvent("UIEvents"),d.initUIEvent(c,k,k,window,1));b.dispatchEvent(d)})};function rd(b){var c={schema:{},sync:m,attr:{}};b||(b={});b.attr=b.attr||{};S(b,function(d,e){q(c[e])||(b.attr[e]=d)});S(c,function(d,e){c[e]=b[e]||c[e]});this.z={};this.W={};this.h=c.schema||{};this.hc=c.sync;this.ta=[];this.Oa={};this.bb=[];this.Tb=fa;Tb(this,"change",this.Pa,n,this);this.wa=""+A(this);this.set(c.attr);this.dispatchEvent("load")}D(rd,ec);
function sd(b,c){var d=c;if(x(c)){var e={number:ha,string:x,array:v};return function(b){e[c.toLowerCase()](b)||i(new td);return b}}if(d.exec)return B(function(b,c){b.exec(c)===m&&i(new td);return c},b,c);y(d)&&Jb(d.prototype).length&&(d=function(b){z(b)||i(new td);var d=Object.getPrototypeOf(b).constructor;if(Object.getPrototypeOf(b).constructor==c)return b;for(;d.f;)if(d=d.f.constructor,d==c)return b;i(new td)});return d}o=rd.prototype;
o.get=function(b,c){if(t(b))return Ca(b,function(b,d){b[d]=this.get(d,c);return b},this);if(this.h[b]&&this.h[b].get){var d=this.h[b].get.apply(this,I(this.h[b].gb||[],function(d){if(d===b)return this.z[b];d=this.get(d);return q(d)?d:c},this));return q(d)?d:c}return q(this.z[b])?this.z[b]:c};
o.set=function(b,c,d){var e=n;if(x(b)){var g={};g[b]=c;b=g}else d=c;S(b,function(b,c){if(q(b))try{this.z[c]=this.h[c]&&this.h[c].set?sd(this,this.h[c].set).call(this,b,d):b;var g=this.h[c];if(q(g)&&y(g.Ra)){var r=g.Ra;y(r)&&!r(this.get(c),this.V(c))&&(e=k)}else this.get(c)!==this.V(c)&&(e=k)}catch(s){s.ac?this.Tb(s):i(s)}else this.z[c]=b,this.W[c]!=this.z[c]&&(e=k)},this);return e?(d||(this.dispatchEvent("change"),this.W=Ob(this.z),this.z=Gb(this.z,function(b){return q(b)})),k):n};
o.la=function(){this.dispatchEvent("change");this.W=Ob(this.z)};o.V=function(b){return this.h[b]&&this.h[b].get?this.h[b].get.apply(this,I(this.h[b].gb||[],function(c){return c===b?this.W[b]:this.V(c)},this)):this.W[b]};function ud(b){b.h.farenheit||(b.h.farenheit={});b.h.farenheit.get=aa();b.h.farenheit.set=function(b,d){this.set("temp",b,d)};b.h.farenheit.gb=["temp"]}
function vd(b){var c=Jb(Gb(b.h,function(b,c){var g=this.h[c];if(g.Ra)return!g.Ra(this.V(c),this.get(c));g=this.V(c);return t(g)?!Ta(g,this.get(c)):this.V(c)!=this.get(c)},b));Ra(c,Jb(Gb(b.z,function(b,c){return q(this.h[c])?n:t(b)?!Ta(b,this.W[c]):b!==this.W[c]},b)));return c}o.J=function(b,c){b&&this.hc.nc(this,c);this.dispatchEvent("unload");H(L(this.bb),function(b){b(this)},this);this.t()};
o.Pa=function(){var b=vd(this);H(this.ta,function(c){Ha(c.r,function(c){return 0<=G(b,c)})&&c.p.apply(c.wb,Qa(I(c.r,function(b){return this.get(b)},this)))},this);b.length&&S(this.Oa,function(b){b(this)},this)};o.Na=function(b,c){var b=B(b,c||this),d=A(b);this.bb.push(b);var e={n:function(){b();return e},id:d,b:B(this.b,this,d)};return e};
o.bind=function(b,c,d){x(b)&&(b=[b]);var e={r:b,p:c,wb:d||this};e.Qa=A(e);this.ta.push(e);var g={n:B(function(){var e=I(b,function(b){return this.get(b)},this);e.push(this);c.apply(d||this,e);return g},this),id:e.Qa,b:B(this.b,this,e.Qa)};return g};o.b=function(b){z(b)&&b.id&&(b=b.id);return J(this.ta,function(c){return c.Qa==b})||Kb(this.Oa,b)||J(this.bb,function(c){return A(c)==b})};
o.Ma=function(b,c){var d=B(b,c||this),e=A(d);this.Oa[""+e]=d;var b=B(b,c||this,this),g={n:function(){b();return g},id:e,b:B(this.b,this,e)};return g};function td(){this.ac=k}D(td,Error);function wd(b){b=b||{};jd.extend(b,{schema:xd});rd.call(this,b);ud(this)}D(wd,rd);var xd={celcius:{get:function(b){return 5/9*(b-32)},set:function(b,c){this.set("temp",9*b/5+32,c)},gb:["temp"]}};function yd(b){this.Z={};this.N={};b&&(this.pa=b.split||this.pa,this.Ia=b.Bc||this.Ia,this.jb=b.Cc||this.jb);this.kc=RegExp(ya(ya(this.Ia)),"gi");this.Gb=RegExp(ya(ya(this.jb)),"gi")}o=yd.prototype;o.pa=".";o.Ia="*";o.jb="%";function zd(b){var c=Ad,d="chooseCity";b.ua||(b.ua=B(c.ua,c));v(d)||(d=[d]);H(d,function(c){this.Z[c]=this.Z[c]||[];Ma(this.Z[c],b);1==this.Z[c].length&&S(this.N,function(d,f){H(d,function(d){!d.Zb&&Bd(this,f,c)&&(d.Zb=k,d.oc=n,d.M&&d.M([b]))},this)},this)},c)}
function Cd(b,c,d){c=ya(c);c=c.replace(b.kc,".*").replace(b.Gb,"[^"+b.pa+"]*");return!!d.match(RegExp("^"+c+"$","i"))}function Bd(b,c,d){var e=c.indexOf(b.Ia),g;-1<e&&(g=c.substring(0,e));g=c.split(b.pa);return Ia(d.split(b.pa),function(b,c){if(!g[c])return k;var d=RegExp("^"+ya(g[c]).replace(this.Gb,".*")+"$","i");return b.match(d)||-1<e&&b.match(d)?k:n},b)}
o.q=function(b,c,d){if(v(b))return H(b,function(b){this.q(b,c,d)},this),m;this.N[b]=this.N[b]||[];this.N[b].length||c.M&&this.Z[b]&&c.M(this.Z[b][0]);y(c)&&(c={p:c});c.p=B(c.p,d||this);c.id=d||this;Ma(this.N[b],c);return A(c)};o.P=function(b){var c=[];S(this.N,function(d,e){for(;J(d,function(c){return A(c)==b||c.id==b}););d.length||c.push(e)});H(c,function(b){delete this.N[b]},this);return n};
o.ua=function(b,c){S(this.N,function(d,e){Cd(this,e,b)&&H(d.slice(),function(d){y(d)?d(c,b):d.p&&d.p(c,b)})},this)};function Dd(b){this.$={};this.Qb=b||rd}Dd.prototype.get=function(b,c){if(this.$[b])return this.$[b];var d=new (c||this.Qb);b&&d.set("id",b,k);this.$[b||d.wa]=d;var e=Tb(d,"change",function(){var b=d.get("id");b&&(this.$[b]=d,delete this.$[d.wa],Yb(e))},n,this);return d};Dd.prototype.set=function(b){v(b)||(b=[b]);H(b,function(b){this.$[b.get("id")||b.wa]=b},this)};var Ad=new yd,Ed=new Dd(wd);function Fd(b){this.Vb=b;this.j=[]}D(Fd,na);var Gd=[];function pd(b,c,d,e,g,f){t(d)||(Gd[0]=d,d=Gd);for(var h=0;h<d.length;h++)b.j.push(Tb(c,d[h],e||b,g||n,f||b.Vb||b));return b}function Hd(b){H(b.j,Yb);b.j.length=0}Fd.prototype.t=function(){Fd.f.t.call(this);Hd(this)};Fd.prototype.handleEvent=function(){i(Error("EventHandler.handleEvent not implemented"))};function Id(){}(function(b){b.vb=function(){return b.$b||(b.$b=new b)}})(Id);Id.prototype.cc=0;Id.vb();function Jd(b){this.ma=b||oc()}D(Jd,ec);o=Jd.prototype;o.Wb=Id.vb();o.ga=m;o.l=n;o.k=m;o.e=m;o.v=m;o.c=m;o.o=m;o.Fb=n;function Kd(b){return b.ga||(b.ga=":"+(b.Wb.cc++).toString(36))}o.B=da("k");o.Fa=ba("k");function Ld(b,c){b==c&&i(Error("Unable to set parent component"));c&&b.v&&b.ga&&b.v.o&&b.ga&&b.ga in b.v.o&&b.v.o[b.ga]&&b.v!=c&&i(Error("Unable to set parent component"));b.v=c;Jd.f.hb.call(b,c)}o.getParent=da("v");
o.hb=function(b){this.v&&this.v!=b&&i(Error("Method not supported"));Jd.f.hb.call(this,b)};o.T=function(){this.k=this.ma.createElement("div")};function Md(b){Nd(b,document.body)}function Nd(b,c,d){b.l&&i(Error("Component already rendered"));b.k||b.T();c?c.insertBefore(b.k,d||m):b.ma.K.body.appendChild(b.k);(!b.v||b.v.l)&&b.A()}
function Od(b){var c=Y(".single")[0];b.l&&i(Error("Component already rendered"));if(c&&b.rb(c)){b.Fb=k;if(!b.ma||b.ma.K!=qc(c))b.ma=oc(c);b.Ta(c);b.A()}else i(Error("Invalid element to decorate"))}o.rb=function(){return k};o.Ta=ba("k");o.A=function(){this.l=k;Pd(this,function(b){!b.l&&b.B()&&b.A()})};function Qd(b){Pd(b,function(b){b.l&&Qd(b)});b.ea&&Hd(b.ea);b.l=n}
o.t=function(){Jd.f.t.call(this);this.l&&Qd(this);this.ea&&(this.ea.J(),delete this.ea);Pd(this,function(b){b.J()});!this.Fb&&this.k&&Dc(this.k);this.v=this.e=this.k=this.o=this.c=m};o.Ga=ba("e");
o.ka=function(b,c,d){b.l&&(d||!this.l)&&i(Error("Component already rendered"));(0>c||c>(this.c?this.c.length:0))&&i(Error("Child component index out of bounds"));if(!this.o||!this.c)this.o={},this.c=[];b.getParent()==this?(this.o[Kd(b)]=b,Pa(this.c,b)):Lb(this.o,Kd(b),b);Ld(b,this);Na(this.c,b,c);b.l&&this.l&&b.getParent()==this?(d=this.ca(),d.insertBefore(b.B(),d.childNodes[c]||m)):d?(this.k||this.T(),c=this.c?this.c[c+1]||m:m,Nd(b,this.ca(),c?c.k:m)):this.l&&!b.l&&b.k&&b.A()};o.ca=da("k");
function Pd(b,c){b.c&&H(b.c,c,j)}o.removeChild=function(b,c){if(b){var d=x(b)?b:Kd(b),b=this.o&&d?(d in this.o?this.o[d]:j)||m:m;d&&b&&(Kb(this.o,d),Pa(this.c,b),c&&(Qd(b),b.k&&Dc(b.k)),Ld(b,m))}b||i(Error("Child is not in parent component"));return b};function Z(b){Z.f.constructor.apply(this,M(arguments,1));this.u={Wa:{},L:{}};this.na=[];this.sa=[];this.Ga(b);this.ya=m}D(Z,Jd);o=Z.prototype;o.Fa=function(b){Z.f.Fa.call(this,b);this.ya||(this.ya=b)};o.ca=function(){return this.ya||Z.f.ca.call(this)};
o.Ga=function(b,c){this.e&&H(I(this.na,function(b){return b.id}),this.Db,this);Z.f.Ga.call(this,b);H(this.na,function(b){var e=b.p.apply(this,b.Ib);b.bound=e;b.n=e.n;b.b=B(this.b,this,e.id);b.id=e.id;!c&&!(0<=G([this.mb,this.ob,this.pb],b.p))&&b.n()},this)};o.remove=function(){Dc(this.B());this.J()};
o.Ub=function(b,c){this.u.L[b]&&H(this.u.L[b],function(b){if(!c.Q&&(!b.Cb.length||Ha(b.Cb,function(b){if(y(b))return b(c);if(b=Ja($(this,b),function(b){return Fc(b,c.target)}))c.target=b;return b},this)))b.p.call(b.fa,c),b.stop&&c.stopPropagation()},this)};
o.q=function(b,c,d,e,g,f){var h=["blur","focus"];this.u||(this.u={Wa:{},L:{}});this.u.L[b]||(this.u.L[b]=[]);this.u.Wa[b]||(this.u.Wa[b]=pd(this.ea||(this.ea=new Fd(this)),this.B(),b,B(this.Ub,this,b),0<=G(h,b)));q(d)||(d=[]);d={Cb:t(d)?d:[d],p:c,Ha:m,fa:e||this,fc:g||50,stop:f};d.Ha=A(d);Na(this.u.L[b],d,La(this.u.L[b],function(b){return b.fc<=(g||50)})+1);var l={n:B(function(d){var f=this.B();d&&(f=d);c.call(e||this,new Ab(b,f));return l},this),id:d.Ha,P:B(this.P,this,d.Ha)};return l};
o.click=function(b,c,d,e,g){return this.q("click",b,c,d,e,g)};o.P=function(b){z(b)&&b.id&&(b=b.id);S(this.u.L,function(c){J(c,function(c){return c.Ha==b})})};
function $(b,c){var d;d=d||b.B();if(!c)return[d];if(t(c))return d=Wa(I(c,function(b){return $(this,b)},b)),Sa(d),d;"-"==c.charAt(0)&&(c="."+c.substring(1));return"."==c.charAt(0)?tc(c.substring(1),d)||[]:"#"==c.charAt(0)?[x(c.substring(1))?document.getElementById(c.substring(1)):c.substring(1)]:L(rc(pa(c.replace(/\..*/,"")),0<c.indexOf(".")?c.replace(/.*\./,""):m,d))}
function Rd(b,c){var d=Sd;c&&(b.ya=c);b.Za(function(){var b=Td(this.e),c=this.c||[],f=I(c,function(b){return b.e}),h=Ba(c,function(c){return!(0<=G(b,c.e))});0==c.length?H(b,function(b){this.ka(new d(b),this.c?this.c.length:0,k)},this):(H(h,function(b){this.removeChild(b,k)},this),H(b,function(b,e){if(0<=G(f,b))h=Ja(c,function(c){return c.e==b}),(this.c?this.c[e]||m:m)!=h&&this.ka(h,e);else{var h=new d(b);h.T();this.ka(h,e,k)}},this))}).n()}
o.Jb=function(b,c){var d=M(arguments,2)[0];if(b.qa){var e={};b.data&&S(b.data,function(b,c){e[c]=y(b)?b(this):c},this);e.D=this.e.get(b.m);var g=b.qa(e);H($(this,c),function(b){"INPUT"==b.tagName&&"checkbox"!=b.getAttribute("type")?b.value!=g&&(b.value=g):"SELECT"==b.tagName?H(b.options,function(b){b.selected=b.value==g}):(Bc(b),Ac(b,zc(g)))},this)}H($(this,c),function(c){"INPUT"==c.tagName&&"checkbox"==c.getAttribute("type")&&(c.checked=this.e.get(b.m[0]))},this);if(q(b.ab)){var f=b.ab;H($(this,
c),function(c){var e=f;d?kc(c,e):lc(c,e);b.dc&&(e=b.dc,!d?kc(c,e):lc(c,e))})}b.R&&(t(b.R)?H($(this,c),function(c){H(b.R,function(e){e==b.va(d)?kc(c,e):lc(c,e)},this)},this):H($(this,c),function(c){S(b.R,function(e,f){f==b.va(d)?kc(c,e):lc(c,e)},this)},this));b.show&&H($(this,c),function(c){var e=b.show(d);c.style.display=e?"":"none"});if(b.r){var h={};h[b.r]=this.e.get(b.m[0]);H($(this,c),function(c){q(h[b.r])?vc(c,h):c.removeAttribute(b.r)})}b.ic&&b.ic.apply(this,I(b.m,function(){return this.e.get("key")},
this))};
function Ud(b,c,d){x(d)&&(d={qa:d});if(x(d.qa)){var e=d.qa,g=e.match(/\{\$([^}]*)\}/g)||[],g=I(g,function(b){return b.substring(2,b.length-1)});d.qa=function(b){var c=e;S(b.D,function(b,d){c=c.replace(RegExp("\\{\\$"+d+"\\}","g"),b)});return c};d.m=d.m||[];Ra(d.m,g);Sa(d.m)}d.R&&(d.va||(d.va=aa()),x(d.R)&&(d.R=[d.R]));d.show&&(d.m||(d.m=[]),x(d.show)&&Na(d.m,d.show,0),y(d.show)||(d.show=aa()));t(d.m)||(d.m=[d.m]);var f=[];q(d.sc)||f.push(b.q("blur",function(b){"INPUT"==b.target.tagName&&"text"==b.target.getAttribute("type")?
this.e.set(d.m[0],b.target.value):"SELECT"==b.target.tagName&&this.e.set(d.m[0],b.target.options[b.target.selectedIndex].value)},c));q(d.tc)||f.push(b.click(function(b){d.ab?(this.e.set(d.m[0],!(0<=G(jc(b.target),d.ab))),b.stopPropagation()):"INPUT"==b.target.tagName&&"checkbox"==b.target.getAttribute("type")&&(this.e.set(d.m[0],b.target.checked),b.stopPropagation())},c,b,30));g=b.bind(d.m,function(){this.Jb.apply(this,Qa([d,c],L(arguments)))}).n();g={id:A(f),Mb:f,bound:g,n:g.n,b:B(function(){this.b(A(f))},
b)};b.sa.push(g)}o.bind=function(b,c,d){return Vd(this,this.Lb,M(arguments,0))};o.Lb=function(b,c,d){return this.e.bind(b,c,d||this)};o.Ma=function(b,c){return Vd(this,this.Kb,M(arguments,0))};o.Kb=function(b,c){return this.e.Ma(b,c||this)};o.lb=function(b,c){return Vd(this,this.mb,M(arguments,0))};o.mb=function(b,c){return this.e.lb(b,c||this)};o.nb=function(b,c){return Vd(this,this.ob,M(arguments,0))};o.ob=function(b,c){return this.e.nb(b,c||this)};
o.Na=function(b,c){return Vd(this,this.pb,M(arguments,0))};o.pb=function(b,c){return this.e.Na(b,c||this)};function Vd(b,c,d){var e=c.apply(b,d||[]),c={id:e.id,bound:e,n:e.n,b:B(b.b,b,e.id),p:c,Ib:d||[]};b.na.push(c);return c}o.kb=function(b,c){return Vd(this,this.Y,M(arguments,0))};o.Y=function(b,c){return this.e.kb(b,c||this)};o.Za=function(b,c){return Vd(this,this.O,M(arguments,0))};o.O=function(b,c){return this.e.Za(b,c||this)};
o.b=function(b){J(this.na,function(c){z(c)&&(c=c.id);return c==(b.id||b)});var c=Ja(this.sa,function(c){return c.id==(b.id||b)});c&&(H(c.Mb,function(b){this.P(b)},this),b=c.bound);Pa(this.sa,c);return this.Db(b)};o.Db=function(b){return this.e.b(b)};o.t=function(){H(L(this.na),function(b){b.b()},this);this.u=m;H(L(this.sa),function(b){b.b()});Z.f.t.call(this)};
o.ka=function(b,c,d){if(N&&!P(9))Z.f.ka.call(this,b,c,d);else{b.l&&(d||!this.l)&&i(Error("Component already rendered"));(0>c||c>(this.c?this.c.length:0))&&i(Error("Child component index out of bounds"));if(!this.o||!this.c)this.o={},this.c=[];b.getParent()==this?(Mb(this.o,Kd(b),b),Pa(this.c,b)):Lb(this.o,Kd(b),b);Ld(b,this);Na(this.c,b,c);if(d&&(!b.Yb||!this.Yb||b.getParent!=this)){this.k||this.T();var e=this.c?this.c[c+1]||m:m;Nd(b,this.ca(),e?e.k:m)}b.l&&this.l&&b.getParent()==this?(d=this.ca(),
this.Da?H(this.c,function(b,c){this.Da(0,b,c)},this):d.insertBefore(b.B(),d.childNodes[c]||m)):!d&&this.l&&!b.l&&b.k&&b.k.parentNode&&b.A()}};o.removeChild=function(b,c){var d=Z.f.removeChild.call(this,b,c);this.Da&&H(this.c,function(b,c){this.Da(0,b,c)},this);return d};function Sd(b){Z.call(this,b);zd(this)}D(Sd,Z);Sd.prototype.T=function(){this.Fa(Y('<div><div class="city"></div><div class="temp"></div></div>')[0])};Sd.prototype.A=function(){Sd.f.A.call(this);Ud(this,".city","City: {$city}");Ud(this,".temp","{$farenheit} &deg;F");this.bind("temp",function(b){ld(Y(this.B()),"left",10*b-300)}).n();this.click(function(){this.ua("chooseCity",this.e.get("id"))});Ud(this,"",{m:["celcius"],R:["hot","mild"],va:function(b){if(30<b)return"hot";if(20>b)return"mild"}})};N&&P(8);"ScriptEngine"in p&&"JScript"==p.ScriptEngine()&&(p.ScriptEngineMajorVersion(),p.ScriptEngineMinorVersion(),p.ScriptEngineBuildVersion());function Wd(b){Z.call(this,b);b.xa=Xd;b.sort(j)}D(Wd,Z);function Xd(b,c){return b.get("city")>c.get("city")||(b.get("city")==c.get("city"))-1}var Yd={ALPHA:Xd,TEMP:function(b,c){return c.get("temp")-b.get("temp")}};Wd.prototype.T=function(){this.Fa(Y('<div class="list"><select class="sort"><option value="ALPHA" selected>Alphabetical</option><option value="TEMP">Highest Temperature</option><select><div class="content"></div></div>')[0])};
Wd.prototype.A=function(){Wd.f.A.call(this);var b=$(this,".content")[0];Rd(this,b);this.q("change",this.Nb,".sort")};Wd.prototype.Nb=function(b){var c=this.e,b=Yd[md(Y(b.target))];c.xa=b;c.sort(j)};Wd.prototype.Da=function(b,c,d){ld(Y(c.B()),{top:45*d})};function Zd(b){Z.call(this,b)}D(Zd,Z);Zd.prototype.rb=function(b){return Y(".city",b).size()&&Y(".temp",b).size()&&Y(".celcius",b).size()};Zd.prototype.Ta=function(b){return Zd.f.Ta.call(this,b)};Zd.prototype.A=function(){Zd.f.A.call(this);Ud(this,".city","{$city}");Ud(this,".temp","{$farenheit}");Ud(this,".celcius","{$celcius}");this.q("keyup",function(b){13===b.keyCode&&b.target.blur()},"input")};function $d(){return k};/*
 Portions of this code are from the Dojo Toolkit, received by
 The Closure Library Authors under the BSD license. All other code is
 Copyright 2005-2009 The Closure Library Authors. All Rights Reserved.

 The "New" BSD License:

 Copyright (c) 2005-2009, The Dojo Foundation
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.
 Neither the name of the Dojo Foundation nor the names of its contributors
 may be used to endorse or promote products derived from this software
 without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
var kd=function(){function b(b,d){if(!b)return[];if(b.constructor==Array)return b;if(!x(b))return[b];if(x(d)&&(d=x(d)?document.getElementById(d):d,!d))return[];var d=d||document,f=d.ownerDocument||d.documentElement;Ea=d.contentType&&"application/xml"==d.contentType||hb&&(d.doctype||"[object XMLDocument]"==f.toString())||!!f&&(N?f.xml:d.xmlVersion||f.xmlVersion);return(f=e(b)(d))&&f.Aa?f:c(f)}function c(b){if(b&&b.Aa)return b;var c=[];if(!b||!b.length)return c;b[0]&&c.push(b[0]);if(2>b.length)return c;
ca++;if(N&&Ea){var d=ca+"";b[0].setAttribute("_zipIdx",d);for(var e=1,f;f=b[e];e++)b[e].getAttribute("_zipIdx")!=d&&c.push(f),f.setAttribute("_zipIdx",d)}else if(N&&b.Ob)try{for(e=1;f=b[e];e++)pb(f)&&c.push(f)}catch(g){}else{b[0]&&(b[0]._zipIdx=ca);for(e=1;f=b[e];e++)b[e]._zipIdx!=ca&&c.push(f),f._zipIdx=ca}return c}function d(b,c){if(!c)return 1;var d=de(b);return!c[d]?c[d]=1:0}function e(b,c){if($c){var d=ad[b];if(d&&!c)return d}if(d=bd[b])return d;var d=b.charAt(0),f=-1==b.indexOf(" ");0<=b.indexOf("#")&&
f&&(c=k);if($c&&!c&&-1==">~+".indexOf(d)&&(!N||-1==b.indexOf(":"))&&!(cd&&0<=b.indexOf("."))&&-1==b.indexOf(":contains")&&-1==b.indexOf("|=")){var h=0<=">~+".indexOf(b.charAt(b.length-1))?b+" *":b;return ad[b]=function(c){try{9==c.nodeType||f||i("");var d=c.querySelectorAll(h);N?d.Ob=k:d.Aa=k;return d}catch(g){return e(b,k)(c)}}}var l=b.split(/\s*,\s*/);return bd[b]=2>l.length?g(b):function(b){for(var c=0,d=[],e;e=l[c++];)d=d.concat(g(e)(b));return d}}function g(b){var c=dd(pa(b));if(1==c.length){var d=
f(c[0]);return function(b){if(b=d(b,[]))b.Aa=k;return b}}return function(b){for(var b=$a(b),d,e,g=c.length,h,Da,cc=0;cc<g;cc++){Da=[];d=c[cc];e=b.length-1;0<e&&(h={},Da.Aa=k);e=f(d);for(var l=0;d=b[l];l++)e(d,Da,h);if(!Da.length)break;b=Da}return Da}}function f(b){var c=ed[b.ia];if(c)return c;var d=b.xb,d=d?d.Ba:"",e=s(b,{aa:1}),f="*"==b.s,g=document.getElementsByClassName;if(d)g={aa:1},f&&(g.s=1),e=s(b,g),"+"==d?c=r(e):"~"==d?c=l(e):">"==d&&(c=h(e));else if(b.id)e=!b.zb&&f?$d:s(b,{aa:1,id:1}),c=
function(c,d){var f=oc(c).B(b.id),g;if(g=f&&e(f))if(!(g=9==c.nodeType)){for(g=f.parentNode;g&&!(g==c);)g=g.parentNode;g=!!g}if(g)return $a(f,d)};else if(g&&/\{\s*\[native code\]\s*\}/.test(""+g)&&b.F.length&&!cd)var e=s(b,{aa:1,F:1,id:1}),u=b.F.join(" "),c=function(b,c){for(var d=$a(0,c),f,g=0,h=b.getElementsByClassName(u);f=h[g++];)e(f,b)&&d.push(f);return d};else!f&&!b.zb?c=function(c,d){for(var e=$a(0,d),f,g=0,h=c.getElementsByTagName(b.Va());f=h[g++];)e.push(f);return e}:(e=s(b,{aa:1,s:1,id:1}),
c=function(c,d){for(var f=$a(0,d),g,h=0,ce=c.getElementsByTagName(b.Va());g=ce[h++];)e(g,c)&&f.push(g);return f});return ed[b.ia]=c}function h(b){b=b||$d;return function(c,e,f){for(var g=0,h=c[fd];c=h[g++];)ab(c)&&(!f||d(c,f))&&b(c,g)&&e.push(c);return e}}function l(b){return function(c,e,f){for(c=c[bb];c;){if(ab(c)){if(f&&!d(c,f))break;b(c)&&e.push(c)}c=c[bb]}return e}}function r(b){return function(c,e,f){for(;c=c[bb];)if(!qb||pb(c)){(!f||d(c,f))&&b(c)&&e.push(c);break}return e}}function s(b,c){if(!b)return $d;
var c=c||{},d=m;c.aa||(d=Fa(d,pb));c.s||"*"!=b.s&&(d=Fa(d,function(c){return c&&c.tagName==b.Va()}));c.F||H(b.F,function(b,c){var e=RegExp("(?:^|\\s)"+b+"(?:\\s|$)");d=Fa(d,function(b){return e.test(b.className)});d.count=c});c.X||H(b.X,function(b){var c=b.name;dc[c]&&(d=Fa(d,dc[c](c,b.value)))});c.ra||H(b.ra,function(b){var c,e=b.r;b.type&&gd[b.type]?c=gd[b.type](e,b.Xa):e.length&&(c=ee(e));c&&(d=Fa(d,c))});c.id||b.id&&(d=Fa(d,function(c){return!!c&&c.id==b.id}));d||"default"in c||(d=$d);return d}
function E(b){return W(b)%2}function u(b){return!(W(b)%2)}function W(b){var c=b.parentNode,d=0,e=c[fd],f=b._i||-1,g=c._l||-1;if(!e)return-1;e=e.length;if(g==e&&0<=f&&0<=g)return f;c._l=e;f=-1;for(c=c.firstElementChild||c.firstChild;c;c=c[bb])ab(c)&&(c._i=++d,b===c&&(f=d));return f}function K(b){for(;b=b[bb];)if(ab(b))return n;return k}function hd(b){for(;b=b[fe];)if(ab(b))return n;return k}function Ga(b,c){return!b?"":"class"==c?b.className||"":"for"==c?b.htmlFor||"":"style"==c?b.style.cssText||"":
(Ea?b.getAttribute(c):b.getAttribute(c,2))||""}function pb(b){return 1==b.nodeType}function Fa(b,c){return!b?c:!c?b:function(){return b.apply(window,arguments)&&c.apply(window,arguments)}}function dd(b){function c(){0<=s&&(w.id=d(s,C).replace(/\\/g,""),s=-1);if(0<=u){var b=u==C?m:d(u,C);0>">~+".indexOf(b)?w.s=b:w.Ba=b;u=-1}0<=r&&(w.F.push(d(r+1,C).replace(/\\/g,"")),r=-1)}function d(c,e){return pa(b.slice(c,e))}for(var b=0<=">~+".indexOf(b.slice(-1))?b+" * ":b+" ",e=[],f=-1,g=-1,h=-1,l=-1,r=-1,s=
-1,u=-1,E="",Q="",K,C=0,W=b.length,w=m,R=m;E=Q,Q=b.charAt(C),C<W;C++)if("\\"!=E)if(w||(K=C,w={ia:m,X:[],ra:[],F:[],s:m,Ba:m,id:m,Va:function(){return Ea?this.ec:this.s}},u=C),0<=f)if("]"==Q){R.r?R.Xa=d(h||f+1,C):R.r=d(f+1,C);if((f=R.Xa)&&('"'==f.charAt(0)||"'"==f.charAt(0)))R.Xa=f.slice(1,-1);w.ra.push(R);R=m;f=h=-1}else"="==Q&&(h=0<="|~^$*".indexOf(E)?E:"",R.type=h+Q,R.r=d(f+1,C-h.length),h=C+1);else 0<=g?")"==Q&&(0<=l&&(R.value=d(g+1,C)),l=g=-1):"#"==Q?(c(),s=C+1):"."==Q?(c(),r=C):":"==Q?(c(),l=
C):"["==Q?(c(),f=C,R={}):"("==Q?(0<=l&&(R={name:d(l+1,C),value:m},w.X.push(R)),g=C):" "==Q&&E!=Q&&(c(),0<=l&&w.X.push({name:d(l+1,C)}),w.zb=w.X.length||w.ra.length||w.F.length,w.vc=w.ia=d(K,C),w.ec=w.s=w.Ba?m:w.s||"*",w.s&&(w.s=w.s.toUpperCase()),e.length&&e[e.length-1].Ba&&(w.xb=e.pop(),w.ia=w.xb.ia+" "+w.ia),e.push(w),w=m);return e}function $a(b,c){var d=c||[];b&&d.push(b);return d}var cd=O&&"BackCompat"==document.compatMode,fd=document.firstChild.children?"children":"childNodes",Ea=n,gd={"*=":function(b,
c){return function(d){return 0<=Ga(d,b).indexOf(c)}},"^=":function(b,c){return function(d){return 0==Ga(d,b).indexOf(c)}},"$=":function(b,c){return function(d){d=" "+Ga(d,b);return d.lastIndexOf(c)==d.length-c.length}},"~=":function(b,c){var d=" "+c+" ";return function(c){return 0<=(" "+Ga(c,b)+" ").indexOf(d)}},"|=":function(b,c){c=" "+c;return function(d){d=" "+Ga(d,b);return d==c||0==d.indexOf(c+"-")}},"=":function(b,c){return function(d){return Ga(d,b)==c}}},qb="undefined"==typeof document.firstChild.nextElementSibling,
bb=!qb?"nextElementSibling":"nextSibling",fe=!qb?"previousElementSibling":"previousSibling",ab=qb?pb:$d,dc={checked:function(){return function(b){return b.checked||b.attributes.checked}},"first-child":function(){return hd},"last-child":function(){return K},"only-child":function(){return function(b){return!hd(b)||!K(b)?n:k}},empty:function(){return function(b){for(var c=b.childNodes,b=b.childNodes.length-1;0<=b;b--){var d=c[b].nodeType;if(1===d||3==d)return n}return k}},contains:function(b,c){var d=
c.charAt(0);if('"'==d||"'"==d)c=c.slice(1,-1);return function(b){return 0<=b.innerHTML.indexOf(c)}},not:function(b,c){var d=dd(c)[0],e={aa:1};"*"!=d.s&&(e.s=1);d.F.length||(e.F=1);var f=s(d,e);return function(b){return!f(b)}},"nth-child":function(b,c){if("odd"==c)return E;if("even"==c)return u;if(-1!=c.indexOf("n")){var d=c.split("n",2),e=d[0]?"-"==d[0]?-1:parseInt(d[0],10):1,f=d[1]?parseInt(d[1],10):0,g=0,h=-1;0<e?0>f?f=f%e&&e+f%e:0<f&&(f>=e&&(g=f-f%e),f%=e):0>e&&(e*=-1,0<f&&(h=f,f%=e));if(0<e)return function(b){b=
W(b);return b>=g&&(0>h||b<=h)&&b%e==f};c=f}var l=parseInt(c,10);return function(b){return W(b)==l}}},ee=N?function(b){var c=b.toLowerCase();"class"==c&&(b="className");return function(d){return Ea?d.getAttribute(b):d[b]||d[c]}}:function(b){return function(c){return c&&c.getAttribute&&c.hasAttribute(b)}},ed={},bd={},ad={},$c=!!document.querySelectorAll&&(!O||P("526")),ca=0,de=N?function(b){return Ea?b.getAttribute("_uid")||b.setAttribute("_uid",++ca)||ca:b.uniqueID}:function(b){return b._uid||(b._uid=
++ca)};b.X=dc;return b}();ea("goog.dom.query",kd);ea("goog.dom.query.pseudos",kd.X);function ae(b){var b=b||{},c={comparator:b.comparator||m,modelType:b.modelType||rd,models:b.models||[]};Kb(b,"comparator");Kb(b,"modelType");Kb(b,"models");this.C=[];this.xa=c.comparator;this.$a=[];this.La=[];this.Ka=[];this.Ja=[];this.fb=[];this.eb=[];this.O=n;this.bc=c.modelType;rd.call(this,b);H(c.models,function(b){this.add(b,j,k)},this)}D(ae,rd);o=ae.prototype;
o.sort=function(b){var c=n;if(this.xa){var d=this.xa;this.C.sort(function(b,g){var f=d(b.D,g.D);0<f&&(c=k);return f});this.O=this.O||c}b||this.dispatchEvent("change")};
o.add=function(b,c,d){ha(c)&&0>c&&(c=this.C.length+c);var e=0,g=n;t(b)||(b=[b]);H(b,function(d){d instanceof rd||(d=new this.bc(d));if(!Ja(this.C,function(b){return b.D==d})){this.Y=this.O=g=k;var h=d.Ma(B(function(){this.Y=k;this.sort()},this)),l=d.Na(function(){this.remove(b)},this);Na(this.C,{D:d,jc:l,la:h},ha(c)?c+e:this.C.length);e+=1;Ma(this.Ka,d)}},this);this.length=this.C.length;this.sort(k);g&&!d&&this.la();return g};
o.remove=function(b,c){t(b)||(b=[b]);var d=n;H(b,function(b){var c=Ja(this.C,function(c){return c.D==b});c&&(this.Y=this.O=k,b.b(c.jc),b.b(c.la),Pa(this.C,c),d=k,Ma(this.fb,{D:b,id:b.get("id")||b.wa}))},this);this.length=this.C.length;d&&this.sort(k);d&&!c&&this.la();return d};function Td(b){var c;if(x(c)){var d=c;c=function(b){return b.get(d)}}b=I(b.C,function(b){return b.D});return c?Ba(b,c):b}o.indexOf=function(b){return G(Td(this),b)};
o.Za=function(b,c){var d=B(b,c||this);this.$a.push(d);var d=A(d),b=B(b,c||this,this),e={n:function(){b();return e},id:d,b:B(this.b,this,d)};return e};o.kb=function(b,c){var d=B(b,c||this);this.La.push(d);var d=A(d),b=B(b,c||this,this),e={n:function(){b();return e},id:d,b:B(this.b,this,d)};return e};o.lb=function(b,c){var d=B(b,c||this);this.Ja.push(d);var d=A(d),b=B(b,c||this,this),e={n:function(){b();return e},id:d,b:B(this.b,this,d)};return e};
o.nb=function(b,c){var d=B(b,c||this);this.eb.push(d);var d=A(d),b=B(b,c||this,this),e={n:function(){b();return e},id:d,b:B(this.b,this,d)};return e};o.b=function(b){z(b)&&b.id&&(b=b.id);return J(this.$a,function(c){return A(c)==b})||J(this.La,function(c){return A(c)==b})||J(this.eb,function(c){return A(c)==b})||J(this.Ja,function(c){return A(c)==b})||ae.f.b.call(this,b)};
o.Pa=function(){ae.f.Pa.call(this);this.O&&(H(L(this.$a),function(b){b(this)},this),this.O=n);this.Y&&(H(L(this.La),function(b){b(this)},this),this.h&&S(this.h,function(b,c){b.rc&&H(this.ta,function(b){0<=G(b.r,c)&&b.p.apply(b.wb,Qa(I(b.r,function(b){return this.get(b)},this)))},this)},this),this.Y=n);H(this.eb,function(b){H(this.fb,function(c){b(c.D,c.id)})},this);this.fb=[];H(this.Ja,function(b){H(this.Ka,function(c){b(c)})},this);this.Ka=[]};function be(){jd.gc();var b=new ae({modelType:wd});window.a=b;jd.i(be.Hb,function(c){var d=Ed.get(c.id);d.set(c);b.add(d)});var c;try{c=b.C[0].D}catch(d){c=m}var e=new Zd(c);Od(e);Ad.q("chooseCity",function(b){e.Ga(Ed.get(b))});nd().click(function(){Y(Td(b)).i(function(b){b.set("temp",Math.floor(70*Math.random())+30)})});Md(new Wd(b));Y("form").q("submit",function(c){var d=md(Y("form .city")),e=md(Y("form .temp")),l=Ed.get(d);l.set({id:d,city:d,temp:e});b.add(l);c.preventDefault()})}
ea("WeatherDemo.main",be);be.Hb=[{id:"Sydney",city:"Sydney",temp:75},{id:"Melbourne",city:"Melbourne",temp:62},{id:"Brisbane",city:"Brisbane",temp:84},{id:"Perth",city:"Perth",temp:96},{id:"Adelaide",city:"Adelaide",temp:68},{id:"Darwin",city:"Darwin",temp:102},{id:"Hobary",city:"Hobart",temp:35}];